platform :ios,'6.0'

pod 'RestKit'

pod 'JSONKit-NoWarning'

pod 'BlocksKit'

pod 'SDWebImage'

pod 'MagicalRecord'

pod 'SVProgressHUD'

pod 'Appirater'

pod 'RETableViewManager'

pod 'TPKeyboardAvoiding'

pod 'SVPullToRefresh'

pod 'GCPlaceholderTextView'

pod 'UMAnalytics', :git => 'https://github.com/jcccn/UMeng-Analytics-iOS.git'

pod 'UMFeedback', :git => 'https://github.com/jcccn/UMeng-Feedback-iOS.git'
